import { GeoCoordinates } from '@superapp/types';

export interface LocationLandmark {
  id: string;
  name: string;
  category: 'AIRPORT' | 'COMMERCIAL' | 'RESIDENTIAL' | 'HOSPITAL' | 'MALL';
  coordinates: GeoCoordinates;
  address: string;
  city: 'Karachi' | 'Lahore' | 'Islamabad';
}

export const PAKISTANI_LANDMARKS: LocationLandmark[] = [
  // --- NAZIMABAD & NORTH NAZIMABAD ---
  {
    id: 'khi-imran-residency',
    name: 'Imran Residency',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9142, longitude: 67.0278 },
    address: "Fahad's St, Nazimabad 3, Block 3, Nazimabad, Karachi, 74600",
    city: 'Karachi',
  },
  {
    id: 'khi-nazimabad-3',
    name: 'Nazimabad Block 3',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9151, longitude: 67.0274 },
    address: 'Near Altaf Ali Barelvi Rd, Block 3, Nazimabad, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-hamdard-hospital',
    name: 'Hamdard University Hospital (Naimat Begum)',
    category: 'HOSPITAL',
    coordinates: { latitude: 24.9135, longitude: 67.0255 },
    address: 'Taj Jamali Rd, Nazimabad Block 3, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-nazimabad-gymkhana',
    name: 'Nazimabad Gymkhana Cricket Ground',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9168, longitude: 67.0315 },
    address: 'Nawab Siddique Ali Khan Rd, Nazimabad, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-eidgah-nazimabad',
    name: 'Eidgah Ground Nazimabad',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9118, longitude: 67.0275 },
    address: 'Block 3, Nazimabad, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-ao-hospital',
    name: 'A.O. Hospital Nazimabad',
    category: 'HOSPITAL',
    coordinates: { latitude: 24.9192, longitude: 67.0322 },
    address: '4-F, Main Nazimabad No. 4, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-nazimabad-1',
    name: 'Inquiry Office / Nazimabad No. 1',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9082, longitude: 67.0298 },
    address: 'Main Nazimabad Road, Block 1, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-chawla-market',
    name: 'Chawla Market Nazimabad',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9125, longitude: 67.0345 },
    address: 'Block 2, Nazimabad, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-five-star',
    name: 'Five Star Chowrangi',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9362, longitude: 67.0425 },
    address: 'Shahrah-e-Jahangir, North Nazimabad Block D, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-kda-chowrangi',
    name: 'KDA Chowrangi',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9275, longitude: 67.0385 },
    address: 'Block A, North Nazimabad, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-sakhi-hassan',
    name: 'Sakhi Hassan Chowrangi',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9498, longitude: 67.0652 },
    address: 'Shahrah-e-Sher Shah Suri, Block N, North Nazimabad, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-dolmen-hyderi',
    name: 'Dolmen Mall Hyderi',
    category: 'MALL',
    coordinates: { latitude: 24.9320, longitude: 67.0375 },
    address: 'Block H, North Nazimabad, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-hyderi-market',
    name: 'Hyderi Super Market',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9315, longitude: 67.0360 },
    address: 'Block G, North Nazimabad, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-saima-bridge',
    name: 'Saima Bridge View Apartments',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9288, longitude: 67.0345 },
    address: 'Block B, North Nazimabad, Karachi',
    city: 'Karachi',
  },

  // --- CLIFTON & DHA ---
  {
    id: 'khi-clifton-3',
    name: 'Dolmen Mall Clifton',
    category: 'MALL',
    coordinates: { latitude: 24.8138, longitude: 67.0305 },
    address: 'Marine Drive, Block 4, Clifton, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-ocean-mall',
    name: 'Ocean Mall & Tower',
    category: 'MALL',
    coordinates: { latitude: 24.8285, longitude: 67.0345 },
    address: 'Khayaban-e-Iqbal, Block 9, Clifton, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-seaview',
    name: 'Sea View Beach & Promenade',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.7891, longitude: 67.0392 },
    address: 'Abdul Sattar Edhi Ave, DHA Phase 6, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-boat-basin',
    name: 'Boat Basin Food Street',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8242, longitude: 67.0268 },
    address: 'Khayaban-e-Roomi, Block 5, Clifton, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-teen-talwar',
    name: 'Teen Talwar (Three Swords)',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8368, longitude: 67.0315 },
    address: 'Main Clifton Road, Block 8, Clifton, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-dha-5',
    name: 'Khayaban-e-Shahbaz',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.7938, longitude: 67.0674 },
    address: 'DHA Phase 6, Commercial Area, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-bukhari-comm',
    name: 'Bukhari Commercial Area',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.7995, longitude: 67.0620 },
    address: 'DHA Phase 6, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-creek-vistas',
    name: 'Creek Vistas Luxury Apartments',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.7865, longitude: 67.0785 },
    address: 'DHA Phase 8, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-do-darya',
    name: 'Do Darya Coastal Food Avenue',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.7615, longitude: 67.0855 },
    address: 'Abdul Sattar Edhi Ave, DHA Phase 8, Karachi',
    city: 'Karachi',
  },

  // --- SHAHRAH-E-FAISAL & PECHS ---
  {
    id: 'khi-shahrah-faisal',
    name: 'FTC Building / Shahrah-e-Faisal',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8568, longitude: 67.0544 },
    address: 'Shahrah-e-Faisal, Block 7, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-tariq-road',
    name: 'Tariq Road Shopping District',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8718, longitude: 67.0594 },
    address: 'PECHS Block 2, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-rabi-center',
    name: 'Rabi Center Tariq Road',
    category: 'MALL',
    coordinates: { latitude: 24.8725, longitude: 67.0588 },
    address: 'Main Tariq Road, PECHS, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-bahadurabad',
    name: 'Char Minar Chowrangi, Bahadurabad',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8824, longitude: 67.0673 },
    address: 'Bahadurabad, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-naheed',
    name: 'Naheed Supermarket',
    category: 'MALL',
    coordinates: { latitude: 24.8835, longitude: 67.0685 },
    address: 'Main Shaheed-e-Millat Road, Bahadurabad, Karachi',
    city: 'Karachi',
  },

  // --- GULSHAN-E-IQBAL & UNIVERSITY ROAD ---
  {
    id: 'khi-gulshan-iqbal',
    name: 'Disco Bakery / Gulshan Chowrangi',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9189, longitude: 67.0971 },
    address: 'University Road, Block 5, Gulshan-e-Iqbal, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-maskan',
    name: 'Maskan Chowrangi',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9345, longitude: 67.1112 },
    address: 'Block 7, Gulshan-e-Iqbal, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-continental',
    name: 'Continental Bakery Chowk',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9235, longitude: 67.0945 },
    address: 'Block 6, Gulshan-e-Iqbal, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-nipa',
    name: 'NIPA Chowrangi',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9172, longitude: 67.0988 },
    address: 'University Road / Rashid Minhas Rd, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-millennium-mall',
    name: 'Millennium Mall',
    category: 'MALL',
    coordinates: { latitude: 24.8975, longitude: 67.1185 },
    address: 'Rashid Minhas Road, Gulshan-e-Iqbal, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-hasan-square',
    name: 'Hasan Square',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8955, longitude: 67.0735 },
    address: 'University Road, Block 13-D, Gulshan-e-Iqbal, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-expo-centre',
    name: 'Expo Centre Karachi',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8992, longitude: 67.0762 },
    address: 'Main University Road, Gulshan-e-Iqbal, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-saima-royal',
    name: 'Saima Royal Residency',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9258, longitude: 67.0872 },
    address: 'Block 2, Gulshan-e-Iqbal, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-iba-ku',
    name: 'IBA Karachi / University of Karachi',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9419, longitude: 67.1141 },
    address: 'Main University Road, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-aga-khan',
    name: 'Aga Khan University Hospital',
    category: 'HOSPITAL',
    coordinates: { latitude: 24.8924, longitude: 67.0747 },
    address: 'National Stadium Road, Karachi',
    city: 'Karachi',
  },

  // --- GULISTAN-E-JOHAR ---
  {
    id: 'khi-johar',
    name: 'Kamran Chowrangi, Gulistan-e-Johar',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9182, longitude: 67.1354 },
    address: 'Block 12, Gulistan-e-Johar, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-johar-chowrangi',
    name: 'Johar Chowrangi',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9145, longitude: 67.1285 },
    address: 'Block 1, Gulistan-e-Johar, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-samama',
    name: 'Samama Shopping Complex',
    category: 'MALL',
    coordinates: { latitude: 24.9315, longitude: 67.1165 },
    address: 'Main University Road, Gulistan-e-Johar, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-rufi-green',
    name: 'Rufi Green City Apartments',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9265, longitude: 67.1515 },
    address: 'Block 19, Gulistan-e-Johar, Karachi',
    city: 'Karachi',
  },

  // --- FEDERAL B AREA ---
  {
    id: 'khi-lucky-one',
    name: 'Lucky One Mall',
    category: 'MALL',
    coordinates: { latitude: 24.9388, longitude: 67.0869 },
    address: 'LA-2/B, Block 21, Main Rashid Minhas Rd, Federal B Area, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-water-pump',
    name: 'Water Pump Chowrangi',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9312, longitude: 67.0785 },
    address: 'Shahrah-e-Pakistan, FB Area Block 16, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-ayesha-manzil',
    name: 'Ayesha Manzil',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9205, longitude: 67.0665 },
    address: 'Shahrah-e-Pakistan, FB Area Block 7, Karachi',
    city: 'Karachi',
  },

  // --- SADDAR & DOWNTOWN ---
  {
    id: 'khi-empress-market',
    name: 'Empress Market',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8615, longitude: 67.0255 },
    address: 'Preedy Street, Saddar, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-burns-road',
    name: 'Burns Road Food Street',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8586, longitude: 67.0152 },
    address: 'Shahrah-e-Liaquat, Saddar, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-atrium',
    name: 'Atrium Mall & Cinemas',
    category: 'MALL',
    coordinates: { latitude: 24.8525, longitude: 67.0285 },
    address: 'Fatima Jinnah Rd, Saddar, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-iichundrigar',
    name: 'I.I. Chundrigar Road (Wall Street of PK)',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8504, longitude: 67.0011 },
    address: 'I.I. Chundrigar Road, City Railway Colony, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-mazar-quaid',
    name: 'Mazar-e-Quaid (Jinnah Mausoleum)',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8755, longitude: 67.0405 },
    address: 'M.A. Jinnah Road, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-port-grand',
    name: 'Port Grand Food & Culture Hub',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8392, longitude: 66.9942 },
    address: 'Native Jetty Bridge, Keamari, Karachi',
    city: 'Karachi',
  },

  // --- TRANSIT & OUTSKIRTS ---
  {
    id: 'khi-airport',
    name: 'Jinnah International Airport (KHI)',
    category: 'AIRPORT',
    coordinates: { latitude: 24.9065, longitude: 67.1608 },
    address: 'Airport Road, Faisal Cantonment, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-malir-cantt',
    name: 'Malir Cantt Check Post 1 & 2',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9225, longitude: 67.1985 },
    address: 'Malir Cantonment, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-bahria-town',
    name: 'Bahria Town Karachi (Main Gate)',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 25.0112, longitude: 67.3325 },
    address: 'Super Highway (M-9), Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-maymar',
    name: 'Gulshan-e-Maymar (Gate 1)',
    category: 'RESIDENTIAL',
    coordinates: { latitude: 24.9985, longitude: 67.1385 },
    address: 'Super Highway / M-9, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-arena-karsaz',
    name: 'The Arena Karachi (Cinema & Family Recreation)',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8878, longitude: 67.0898 },
    address: 'Habib Ibrahim Rehmatullah Rd, Main Karsaz, Karachi, 75350',
    city: 'Karachi',
  },
  {
    id: 'khi-arena-bahria',
    name: 'The Arena 3D Cinema Bahria Town',
    category: 'COMMERCIAL',
    coordinates: { latitude: 25.0215, longitude: 67.3298 },
    address: 'Midway Commercial, Bahria Town Karachi, M-9 Motorway',
    city: 'Karachi',
  },
  {
    id: 'khi-nueplex-dha',
    name: 'Nueplex Cinemas The Place',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.7862, longitude: 67.0605 },
    address: 'The Place Mall, Khayaban-e-Shaheen, DHA Phase 8, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-nueplex-askari',
    name: 'Nueplex Cinemas Askari IV',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.9082, longitude: 67.1265 },
    address: 'Main Rashid Minhas Road, Askari IV, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-cinepax-ocean',
    name: 'Cinepax Cinemas Ocean Mall',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8285, longitude: 67.0345 },
    address: 'Level 5, Ocean Mall, Khayaban-e-Iqbal, Clifton, Karachi',
    city: 'Karachi',
  },
  {
    id: 'khi-capri-cinema',
    name: 'Capri Cinema Saddar',
    category: 'COMMERCIAL',
    coordinates: { latitude: 24.8672, longitude: 67.0255 },
    address: 'M.A. Jinnah Road, Saddar, Karachi',
    city: 'Karachi',
  },
  {
    id: 'lhr-arena-bahria',
    name: 'The Arena Cinema Bahria Town Lahore',
    category: 'COMMERCIAL',
    coordinates: { latitude: 31.3685, longitude: 74.1895 },
    address: 'Civic Center, Sector F, Bahria Town, Lahore',
    city: 'Lahore',
  },
  {
    id: 'isb-arena-bahria',
    name: 'The Arena 3D Cinema Islamabad / Rawalpindi',
    category: 'COMMERCIAL',
    coordinates: { latitude: 33.5412, longitude: 73.1098 },
    address: 'Phase 4, Civic Center, Bahria Town, Islamabad / Rawalpindi',
    city: 'Islamabad',
  },
  {
    id: 'isb-centaurus-cinema',
    name: 'Centaurus Cineplex Islamabad',
    category: 'COMMERCIAL',
    coordinates: { latitude: 33.7077, longitude: 73.0498 },
    address: '4th Floor, Centaurus Mall, F-8/4, Jinnah Avenue, Islamabad',
    city: 'Islamabad',
  },
  {
    id: 'lhr-mm-alam',
    name: 'M.M. Alam Road Gulberg',
    category: 'COMMERCIAL',
    coordinates: { latitude: 31.5204, longitude: 74.3587 },
    address: 'Gulberg III, Lahore',
    city: 'Lahore',
  },
];
